jobs:
  # All tasks on macOS
  - job: build_all_darwin
    displayName: Build all tasks (macOS)
    timeoutInMinutes: 120
    pool:
      vmImage: macos-latest
    variables:
      CI_TEST: true
    steps:
      - task: UseDotNet@2
        displayName: 'Install .NET Core SDK'
        inputs:
          version: 6.0.x
      - script: bash scripts/install_protobuf.sh
      - script: bash scripts/download_binary.sh
      - script: bash build.sh -target=Run-Unit-Tests
        displayName: 'Build and Test'
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'